version: '3.9'
services:  
  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle install && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./app:/app/app
      - ./config:/app/config
      - ./files:/app/files
      - ./db:/app/db
    ports:
      - "3000:3000"
    entrypoint: ./entrypoints/entrypoint-development.sh
    env_file:
      - .env
    environment:
      - RAILS_ENV=development
    # depends_on:
    #   - uppy_companion
